# User configurations for Ansible VPS setup
admin_username: admin
admin_password: your_secure_password
admin_groups:
  - sudo
  - docker

# SSH Configuration
ssh_public_key_path: ~/.ssh/id_rsa.pub # copy your local SSH public key to this path or update the path accordingly

# Node Js Version
nodejs_version: "20.x"

projects:
  - name: frontend
    repo: "git@github.com:yourusername/frontend-repo.git"
    branch: "main"
    path: "/home/{{ admin_username}}/frontend"
    deploy_key_path: "~/.ssh/frontend_deploy_key" # Path to the deploy key for the frontend repository

  - name: backend
    repo: "git@github.com:yourusername/backend-repo.git"
    branch: "main"
    path: "/home/{{ admin_username }}/backend"
    deploy_key_path: "~/.ssh/backend_deploy_key" # Path to the deploy key for the backend repository

# Firewall configuration
firewall_allowed_ports:
  - 22
  - 80
  - 443
  - 3000
  - 5000
