---
- name: Install and Start The service
  hosts: localhost

  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
    - name: Start nginx service
      service:
        name: nginx
        state: started
      # file create
    - name: Create a sample project directory
      file:
        path: /var/www/html/sample_project
        state: directory
        mode: "0755"
